import Head from "next/head";
import Link from "next/link";
import { useState } from "react";
import Footer from "@/components/Footer";
import { addCampaign, getLastCampaignId } from "../services/Web3Service";


export default function Create(){

    const [campaign, setCampaign] = useState({});
    const [message, setMessage] = useState("");

    function onInputChange(evt) {
        setCampaign(prevState => ({ ...prevState, [evt.target.id]: evt.target.value }));
    }

    function onSaveClick() {
        setMessage("Saving, please wait...");
        addCampaign(campaign)
            .then(tx => getLastCampaignId())
            .then(id => setMessage(`Campaign saved with ID: ${id} Let your friends know and give them that number.`))
            .catch(err => {
                console.error(err);
                setMessage(err.message);
            })
    }

    return (
        <>
            <Head>
                <title>CheapIn - Donate Crypto</title>
                <meta charSet='utf-8' />
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
            </Head>
            <div className='container px-4 py-5'>
                <h1 className='display-5 fw-bold text-body-emphasis lh-1 mb-3'>Create a New Campaign !</h1>
                <p className='lead'>Fill in the fields with your campaign information.</p>
                <p className='lead'>Review carefully, as once recorded on the blockchain they cannot be changed. You will need to create another campaign!</p>
                <hr className="mb-4" />
                <div className="col-6">
                    <div className="form-floating mb-3">
                        <input type="text" id="title" className="form-control" value={campaign.title} onChange={onInputChange} />
                        <label htmlFor="title">Title:</label>
                    </div>
                    <div className="form-floating mb-3">
                        <textarea id="description" className="form-control" value={campaign.description} onChange={onInputChange} />
                        <label htmlFor="description">Description:</label>
                    </div>
                    <div className="form-floating mb-3">
                        <input type="text" id="imageUrl" className="form-control" value={campaign.imageUrl} onChange={onInputChange} />
                        <label htmlFor="imageUrl">Image URL:</label>
                    </div>
                    <div className="form-floating mb-3">
                        <input type="text" id="videoUrl" className="form-control" value={campaign.videoUrl} onChange={onInputChange} />
                        <label htmlFor="videoUrl">Video URL:</label>
                    </div>
                </div>
                <div className="col-6 mb-3">
                    <input type="button" className="btn btn-primary col-12 p-3" value="Save a New Campaign" onClick={onSaveClick} />
                </div>
                <div className="col-6 mb-3">
                    <Link href="/" className="btn btn-secondary col-12 p-3">Back to Home</Link>
                </div>
                {
                    message
                        ? <div className="alert alert-success p-3 col-6" role="alert">{message}</div>
                        : <></>
                }
                <Footer />
            </div>
        </>
    )
}