import Head from "next/head";
import Link from "next/link";
import Footer from "@/components/Footer";
import { useState } from "react";
import { getCampaignById, donate } from "../services/Web3Service";

export default function Donate() {

    const [campaign, setCampaign] = useState({});
    const [donation, setDonation] = useState(0);
    const [message, setMessage] = useState("");

    function onChangeId(evt) {
        campaign.id = evt.target.value;
    }

    function onSearchClick() {
        setMessage("Searching, please wait...");
        getCampaignById(campaign.id)
            .then(result => {
                setMessage("");
                result.id = campaign.id;
                setCampaign(result);
            })
            .catch(err => setMessage(err.message));
    }

    function onChangeValue(evt) {
        setDonation(evt.target.value);
    }

    function btnDonateClick() {
        setMessage("Donating, please wait...");
        donate(campaign.id, donation)
            .then(tx => setMessage(`Donation made, thank you! In a few minutes the balance will be updated.`))
            .catch(err => setMessage(err.message));
    }

    return (
        <>
            <Head>
                <title>CheapIn - Make Donation !</title>
                <meta charSet='utf-8' />
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
            </Head>
            <div className="container">
                <h1 className="display-5 fw-bold text-body-emphasis lh-1 mb-3">Donate Crypto</h1>
                {
                    !campaign.id
                        ? (
                            <>
                                <p className="mb-5">
                                    What is the campaign ID you are looking for?
                                </p>
                                <div className="col-3">
                                    <div className="input-group mb-3">
                                        <input type="number" id="campaignId" className="form-control" onChange={onChangeId} value={campaign.id} />
                                        <input type="button" value="Search" className="btn btn-primary p-3" onClick={onSearchClick} />
                                    </div>
                                </div>
                            </>
                        )
                        : (
                            <>
                                <p>Make sure this is the right campaign before finalizing your donation.</p>
                                <hr />
                                <div className="row flex-lg-row-reverse align-items-center g-5">
                                    <div className="col-7">
                                        {
                                            campaign.videoUrl
                                                ? <iframe width="100%" height="480" src={campaign.videoUrl}></iframe>
                                                : <img src={campaign.imageUrl} className="d-block mx-lg-auto img-fluid" width="640" height="480" />
                                        }
                                    </div>
                                    <div className="col-5 mb-5" style={{ height: 480, scrollbars: true }}>
                                        <h2>{campaign.title}</h2>
                                        <p><strong>Author: </strong>{campaign.author}</p>
                                        <p className="mb-3">{campaign.description}</p>
                                        {
                                            campaign.videoUrl
                                                ? <p>Watch the video on the side to understand more about our campaign.</p>
                                                : <></>
                                        }
                                        <p className="mb-3 fst-italic mt-5">
                                            So, what did you think of the project? has already been collected {campaign.balance / 10 ** 18} BNB in this campaign. how much do you want to donate (in BNB)?
                                        </p>
                                        <div className="mb-3">
                                            <div className="input-group">
                                                <input type="number" id="donation" className="form-control" onChange={onChangeValue} value={donation} />
                                                <span className="input-group-text">BNB</span>
                                                <input type="button" value="Doar" className="btn btn-primary p-3 w-25" onClick={btnDonateClick} />
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </>
                        )
                }
                {
                    message
                        ? <div className="alert alert-success p-3 col-6" role="alert">{message}</div>
                        : <></>
                }
                <Footer />
            </div>
        </>
    )
}